In [1]:
# Import libraries
import pandas as pd

# Create the dataset
data = {
    "Age":[28,45,35,50,30,42,26,48,38,55],
    "AnnualIncome(lakhs)":[6.5,12,8,15,7,10,5.5,14,9,16],
    "CreditScore(300-900)":[720,680,750,640,710,660,730,650,700,620],
    "LoanAmount(lakhs)":[5,10,6,12,5,9,4,11,7,13],
    "LoanTerm(years)":[5,10,7,15,5,10,4,12,8,15],
    "EmploymentType":["Salaried","Self-Employed","Salaried","Self-Employed",
                      "Salaried","Salaried","Salaried","Self-Employed",
                      "Salaried","Self-Employed"],
    "loan(yes/no)":[0,1,0,1,0,1,0,1,0,1]
}

df = pd.DataFrame(data)

print(df)

   Age  AnnualIncome(lakhs)  CreditScore(300-900)  LoanAmount(lakhs)  \
0   28                  6.5                   720                  5
1   45                 12.0                   680                 10
2   35                  8.0                   750                  6
3   50                 15.0                   640                 12
4   30                  7.0                   710                  5
5   42                 10.0                   660                  9
6   26                  5.5                   730                  4
7   48                 14.0                   650                 11
8   38                  9.0                   700                  7
9   55                 16.0                   620                 13

   LoanTerm(years) EmploymentType  loan(yes/no)
0                5       Salaried             0
1               10  Self-Employed             1
2                7       Salaried             0
3               15  Self-Employed             1
4                5       Salaried             0
5               10       Salaried             1
6                4       Salaried             0
7               12  Self-Employed             1
8                8       Salaried             0
9               15  Self-Employed             1

In [2]:
# Encode Employment Type
df["EmploymentType"] = df["EmploymentType"].map({
    "Salaried":0,
    "Self-Employed":1
})
df

,Age,AnnualIncome(lakhs),CreditScore(300-900),LoanAmount(lakhs),LoanTerm(years),EmploymentType,loan(yes/no)
0,28,6.5,720,5,5,0,0
1,45,12.0,680,10,10,1,1
2,35,8.0,750,6,7,0,0
3,50,15.0,640,12,15,1,1
4,30,7.0,710,5,5,0,0
5,42,10.0,660,9,10,0,1
6,26,5.5,730,4,4,0,0
7,48,14.0,650,11,12,1,1
8,38,9.0,700,7,8,0,0
9,55,16.0,620,13,15,1,1

In [3]:
# Separate Features and Target
X = df.drop("loan(yes/no)", axis=1)
y = df["loan(yes/no)"]

In [4]:
X

,Age,AnnualIncome(lakhs),CreditScore(300-900),LoanAmount(lakhs),LoanTerm(years),EmploymentType
0,28,6.5,720,5,5,0
1,45,12.0,680,10,10,1
2,35,8.0,750,6,7,0
3,50,15.0,640,12,15,1
4,30,7.0,710,5,5,0
5,42,10.0,660,9,10,0
6,26,5.5,730,4,4,0
7,48,14.0,650,11,12,1
8,38,9.0,700,7,8,0
9,55,16.0,620,13,15,1

In [5]:
y

0    0
1    1
2    0
3    1
4    0
5    1
6    0
7    1
8    0
9    1
Name: loan(yes/no), dtype: int64

In [6]:
# Split the dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
X_train

,Age,AnnualIncome(lakhs),CreditScore(300-900),LoanAmount(lakhs),LoanTerm(years),EmploymentType
5,42,10.0,660,9,10,0
0,28,6.5,720,5,5,0
7,48,14.0,650,11,12,1
2,35,8.0,750,6,7,0
9,55,16.0,620,13,15,1
4,30,7.0,710,5,5,0
3,50,15.0,640,12,15,1
6,26,5.5,730,4,4,0

In [8]:
X_test

,Age,AnnualIncome(lakhs),CreditScore(300-900),LoanAmount(lakhs),LoanTerm(years),EmploymentType
8,38,9.0,700,7,8,0
1,45,12.0,680,10,10,1

In [9]:
y_train

5    1
0    0
7    1
2    0
9    1
4    0
3    1
6    0
Name: loan(yes/no), dtype: int64

In [10]:
y_test

8    0
1    1
Name: loan(yes/no), dtype: int64

In [11]:
import warnings
warnings.filterwarnings("ignore")

In [12]:
# Normalize the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
# Build the KNN classifier
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [20]:
predictions = model.predict(X_test)

In [21]:
predictions

array([0, 1])

In [24]:
test_accuracy = model.score(X_test, y_test)
print("Test Accuracy:", test_accuracy)

Test Accuracy: 1.0

In [30]:
# Testing code to predict new customer

new_customer = [[40,11,670,10,10,1]] #fake test data

new_customer = scaler.transform(new_customer)

prediction = knn.predict(new_customer)

if prediction[0] == 1:
    print("Loan Default: YES (High Risk Customer)")
else:
    print("Loan Default: NO (Low Risk Customer)")

Loan Default: YES (High Risk Customer)